platform :osx, "10.13"

def pods
  pod "GYDFoundation", 
    :path => "../",
    :testspecs => ['Tests/GYDFoundation','Tests/GYDDatabase','Tests/GYDHTTPConnect','Tests/GYDJSONObject',], 
    :subspecs => ['GYDFoundation', 'GYDDatabase', 'GYDHTTPConnect', 'GYDJSONObject', 'GYDModuleInterface', 'GYDShellTools', 'Development']

  pod "GYDDebugFoundation", 
    :path => "../"

  pod 'GYDFoundationDemo',
    :path => '../'

end

target "MacExample" do 
  pods
end

post_install do |installer|
    installer.pods_project.root_object.attributes["CLASSPREFIX"] = "GYD"
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "宫亚东"
end