platform :ios, "8.0"

def pods
  pod 'GYDFoundation', 
    :path => '../', 
    :testspecs => ['Tests/GYDFoundation','Tests/GYDDatabase','Tests/GYDHTTPConnect','Tests/GYDJSONObject']

  pod 'GYDFoundationDemo',
    :path => '../'

  pod 'GYDDebugFoundation', 
    :git => 'https://gitee.com/pkgogai/gyddebug-foundation_public.git', :tag => '1.0.3'

end

target 'iOSExample' do 
  pods
end

post_install do |installer|
    installer.pods_project.root_object.attributes["CLASSPREFIX"] = "GYD"
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "宫亚东"
end
