platform :ios, "8.0"

def pods
  pod 'GYDFoundation',
    :path => '../',
    :testspecs => ['Tests/GYDFoundation','Tests/GYDDatabase','Tests/GYDHTTPConnect','Tests/GYDJSONObject'],
    :subspecs => ['GYDFoundation', 'GYDDatabase', 'GYDHTTPConnect', 'GYDJSONObject', 'GYDModuleInterface', 'Development']

  pod 'GYDDebugFoundation',
    :path => '../'

  pod 'GYDFoundationDemo',
    :path => '../'

end

target 'iOSExample' do 
  pods
end

post_install do |installer|
    installer.pods_project.root_object.attributes["CLASSPREFIX"] = "GYD"
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "宫亚东"
end
